relies MyGenericList
Dmitry-Ivashkov/ScalaSpbsu21 pull request #3
Opened 2021-03-04 14:45 UTC by Dmitry-Ivashkov

test: add check type, remove sum
@mutcianm @fuCtor

2021-03-15 18:08 UTC, fuCtor requested changes

2021-03-15 18:08 UTC, fuCtor commented on 03/practice/src/main/scala/org/spbsu/mkn/scala/MyGenericList.scala
> +    this match {
зачем это здесь?

2021-03-15 18:08 UTC, fuCtor commented on 03/practice/src/main/scala/org/spbsu/mkn/scala/MyGenericList.scala
> +    this match {
Аналогично.

2021-03-15 18:27 UTC, Dmitry-Ivashkov commented
Там в начале было 2 кейса, убрав 1, забыл убрать ненужную структуру.

2021-03-17 17:51 UTC, fuCtor approved these changes

2021-03-18 14:18 UTC, merged